### ISSUE TITLE
React-router v4

### ISSUE THREAD

**Issue by porfirioribeiro** [brotzky/code-splitting-react-webpack#1]
We are using React Router v4 in our app, 
how could we implement this code splitting with it?

**Comment by brotzky** [comment]
We're using v3 at work so I don't have much experience with v4. I've only used v4 on small personal projects and never tried implementing code splitting.

I am thinking of writing a part 2 version once I get more comfortable with React Router v4. I'm also thinking of adding in a Service Worker guide with pre-cache to build on top of the current guide.

So, I can't help you yet with implementing code splitting with React Router v4 yet. sorry!

**Comment by brotzky** [comment]
Gonna close this for now.
