### ISSUE TITLE
loadRoute 2nd parameter in about page?

### ISSUE THREAD

**Issue by protron** [brotzky/code-splitting-react-webpack#3]
About page route [is using](https://github.com/brotzky/code-splitting/blob/e0e1db9adcbe7fc3c8e73b3711f9b2922692624f/src/routes.js#L41):

          .then(loadRoute(cb, false))

All other pages are passing only the `cb` (as defined in the function definition).
Is that `false` argument really being used?

**Comment by brotzky** [comment]
Great catch. You're correct in assuming the `false` argument is not being used. I'll remove it 👍
