### ISSUE TITLE
Add ES6 sintax

### ISSUE THREAD

**Issue by luisfuertes** [brotzky/code-splitting-react-webpack#4]
I am triying to add ` "babel-preset-es2015": "^6.22.0", `  to add ES6 sintax to my code. But i try to add to my .babelrc
``` 
  "presets": [
    "react",
    "latest",
    "es2015"
  ],
``` 

but my project cant compile with ES6 sintax. 

How can i implement es2015?

**Comment by luisfuertes** [comment]
Ok i solved it with this .babelrc config
``` 
  "presets": [
    "react",
    "latest",
    "es2015",
    "stage-3"
  ],
``` 

package.json
```  
  "babel-preset-es2015": "^6.16.0",
    "babel-preset-stage-3": "^6.16.0",
``` 

and this to webpack.config
``` 
    resolve: {
      extensions: ['.js','.jsx','.json']
    },
```

But on your project example and on my own project, cant load css imported on index.html.

How can i add my css files? I have added this on my webpack.config
``` 
      loaders: [
        {
          test: /\.(js)$/, // look for .js files
          exclude: /node_modules/, // ingore /node_modules
          loader: 'babel-loader', // preprocess with that babel goodness
          query: {
            cacheDirectory: true,
          },
        },
        { test: /\.jsx$/, loader: 'babel-loader', exclude: /node_modules/ },
        { test: /\.css$/, loader: "style-loader!css-loader" }, //Css
```

**Comment by brotzky** [comment]
Thanks for the issue.

I've pushed up support for CSS (including Sass). You can review how it it's done within the webpack config:
https://github.com/brotzky/code-splitting-react-webpack/blob/master/webpack/webpack.config.js

The main changes were within:
```
- /webpack/webpack.config.js
- /src/index.js
- /src/styles/index.scss
```

You can also check the commit diff to see what exactly was added:
https://github.com/brotzky/code-splitting-react-webpack/commit/461bda6cb6d061498f8aabd12553258efc9492f3
