### ISSUE TITLE
Merge conflict in yarn.lock file.

### ISSUE THREAD

**Issue by Alex-Aralis** [brotzky/code-splitting-react-webpack#5]
There is a Merge conflict in yarn.lock line 1968 in master.  

Prevents `yarn install`.

**Comment by brotzky** [comment]
Thanks for reporting this, I wouldn't have found it for a while.

I've removed the conflict and tested that `yarn # or yarn install` work properly.

https://github.com/brotzky/code-splitting-react-webpack/commit/82676ef279d474bbdd6e693c10393c9262c1736e

**Comment by Alex-Aralis** [comment]
No problem, thanks for the guide!
