### ISSUE TITLE
is there a way to achieve two level of routes? such like" <Route path='about/page' ... /> ?"

### ISSUE THREAD

**Issue by brabra** [brotzky/code-splitting-react-webpack#7]
<Route path="/about/page" getComponent = {(location, cb)=>{
                System.import('./components/About')
                    .then(loadRoute(cb))
                    .catch(errorLoading);
            } }/>

**Comment by brotzky** [comment]
This would work with no issues from what I've tried.

```JavaScript
<Route path="/about" getComponent = {(location, cb)=>{
  System.import('./components/About')
      .then(loadRoute(cb))
      .catch(errorLoading);
} }/>
<Route path="/about/page" getComponent = {(location, cb)=>{
  System.import('./components/AboutPage')
      .then(loadRoute(cb))
      .catch(errorLoading);
} }/>
```

**Comment by brabra** [comment]
I did it like you did, but it's not work!, when the path is like "/aaa/bbb", the page is blank, only "/aaa" is working.

**Comment by brabra** [comment]
It can only compile successful, but when I visit 'localhost:3000/about/page', the console report: 'app.d83ec07….js:1 Uncaught SyntaxError: Unexpected token <'

So I have checked the source in console of  'localhost:3000/about/page', I found the 'vendor.***.js' and 'index.***.js' is same as 'index.html', 

their source code:(vendor.***.js, index.***.js, page)

```
<!DOCTYPE html>

<html lang="en">
  <head>
  <title>Code Splitting</title>
  </head>
  <body>
    <!-- The mounting div of our React app -->
    <div id="App"></div>
  <script type="text/javascript" src="vendor.caad40ab705e4f9d77a1.js"></script><script type="text/javascript" src="app.caad40ab705e4f9d77a1.js"></script></body>
</html>

```

**Comment by brotzky** [comment]
Try uncommenting this line:
https://github.com/brotzky/code-splitting-react-webpack/blob/master/webpack/webpack.config.js#L32

It should hopefully solve your issue.

**Comment by brabra** [comment]
Thanks a lot, It's work!😊

**Comment by brotzky** [comment]
You're welcome :)
