### ISSUE TITLE
How should I compile the routes to [name].[chunk].js instead of [number].[chunk].js?

### ISSUE THREAD

**Issue by rashuo** [brotzky/code-splitting-react-webpack#8]
After compile the routes into '/dist', I want to know which one does each routes correspond to.

**Comment by brotzky** [comment]
Hi @rashuo!,
Check this out: https://github.com/webpack/webpack/issues/1949

The main idea is this:
```JavaScript
// in routes
import(/* webpackChunkName: "custom-chunk-name" */ 'path/to/component');
```
```JavaScript
// in webpack config
output: {
  filename: '[name].[chunkhash].js',
  chunkFilename: '[name].[chunkhash].js'
}
```

 If you still need help I'll gladly push up some examples to this repo. Just let me know.

**Comment by rashuo** [comment]
thanks a lot, it's really helpful for me, and i've pushed a PR to this project, if you think it's helpful, you can merge it.

**Comment by brotzky** [comment]
No worries, thanks for the help.
